                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (function(jx){ try {
  var data = [
 ];
  var tgt = $JCA[jx];
  if(tgt.gen && tgt.gen != 0) return;
  var f = function() {
	tgt.setDefaultField("Name", "");
	tgt.setDefaultField("Email", "");
	tgt.setDefaultField("Url", "");
	tgt.newData(data, { "pages": { "sp": 1, "pn": 0, "ps": 15, "tp": 0, "tc": 0 }, "req": { "srt": "date", "ord": "asc", "prs": "thr" }, "avatars": [], "webpresence": [], "identities": [ { "type": "gfc", "group": "third_party", "can_publish": true, "publish": true, "use_as_from": false }, { "type": "twitter", "group": "third_party", "can_publish": true, "publish": true, "use_as_from": false }, { "type": "friendfeed", "group": "third_party", "can_publish": true, "publish": true, "use_as_from": false }, { "type": "yahoo", "group": "third_party", "can_publish": true, "publish": true, "use_as_from": false }, { "type": "blogspot", "group": "native", "can_publish": false, "publish": false, "use_as_from": false }, { "type": "jskit", "group": "native", "can_publish": false, "publish": false, "use_as_from": false }, { "type": "haloscan", "group": "native", "can_publish": false, "publish": false, "use_as_from": false }, { "type": "openid", "group": "native", "can_publish": false, "publish": false, "use_as_from": false } ], "notificationStatus": "unchecked", "htmlMode": true, "uploadImages": true, "skin": "echo", "displayMode": "inline", "popupTitle": "Echo", "popupWidth": "630", "popupHeight": "530", "scoring": true, "commod": true, "extraFieldURL": true, "blogspotLogin": true, "facebookLogin": true, "yahooLogin": true, "twitterLogin": true, "friendfeedLogin": true, "gfcLogin": true, "profile": "SIGSFSDjC.4B0kS8XlcqTA", "TS": 1254830520});
  }
  tgt.newData ? f() : setTimeout(f, 0);
} catch(e){} })(0);
